# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
#  push:
#    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '20 06 * * *'
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    # 设置服务器时区为东八区
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Java Version
      run: java -version
    - name: Run Java
      run: |
           javac src/Main.java
           cd src 
           java Main
    - name: Commit files
      run: |
          git config --local user.email "1402609439@qq.com"
          git config --local user.name "XiaoMing"
          git add .
          git commit -m "`date '+%Y-%m-%d %H:%M:%S'`"
    - name: Push changes
      uses: ad-m/github-push-action@master
#      with:
#      github_token: ${{ secrets.TOKEN }}
#      branch: ${{ github.ref }}
